 * Serving Flask app "start_api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:7489/ (Press CTRL+C to quit)
127.0.0.1 - - [27/Dec/2020 14:30:49] "[37mPOST /verify HTTP/1.1[0m" 200 -
127.0.0.1 - - [27/Dec/2020 14:31:15] "[37mPOST /verify HTTP/1.1[0m" 200 -
[2020-12-27 14:35:33,102] ERROR in app: Exception on /verify [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 124, in read_chunk_len
    _len = int(line.strip(), 16)
ValueError: invalid literal for int() with base 16: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 131, in wrapper
    return f(self, stream, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 253, in _parse_multipart
    form, files = parser.parse(stream, boundary, content_length)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 584, in parse
    return self.cls(form), self.cls(files)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/datastructures.py", line 419, in __init__
    for key, value in mapping or ():
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 582, in <genexpr>
    form = (p[1] for p in formstream if p[0] == "form")
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 537, in parse_parts
    for ellt, ell in self.parse_lines(file, boundary, content_length):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 451, in parse_lines
    terminator = self._find_terminator(iterator)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 368, in _find_terminator
    for line in iterator:
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 721, in make_line_iter
    first_item = next(_iter, "")
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wsgi.py", line 681, in _make_chunk_iter
    item = _read(buffer_size)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 137, in readinto
    self._len = self.read_chunk_len()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 126, in read_chunk_len
    raise IOError("Invalid chunk header")
OSError: Invalid chunk header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 124, in read_chunk_len
    _len = int(line.strip(), 16)
ValueError: invalid literal for int() with base 16: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "start_api.py", line 17, in upload
    audio = request.files['audio']
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/utils.py", line 90, in __get__
    value = self.func(obj)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_request.py", line 514, in files
    self._load_form_data()
  File "/usr/local/lib/python3.6/dist-packages/flask/wrappers.py", line 88, in _load_form_data
    RequestBase._load_form_data(self)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_request.py", line 319, in _load_form_data
    self._get_stream_for_parsing(), mimetype, content_length, options
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 232, in parse
    return parse_func(self, stream, mimetype, content_length, options)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/formparser.py", line 138, in wrapper
    chunk = stream.read(1024 * 64)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 137, in readinto
    self._len = self.read_chunk_len()
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/serving.py", line 126, in read_chunk_len
    raise IOError("Invalid chunk header")
OSError: Invalid chunk header
127.0.0.1 - - [27/Dec/2020 14:35:33] "[35m[1mPOST /verify HTTP/1.1[0m" 500 -
127.0.0.1 - - [27/Dec/2020 14:35:39] "[37mPOST /verify HTTP/1.1[0m" 200 -
